### ISSUE TITLE
RST Documentation & Use 'pass' statement for function stubs and docstrings

### ISSUE THREAD

**Issue by jsbath** [jtannas/NOA#8]
I took a quick look, FYI when you're putting in function stubs (fn signature without body), you use the 'pass' statement instead of 'return'. 🤓

Take a look at using docstrings for your comments too. http://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html

It lets you use introspection (fn.__doc__) and auto make an API index.

**Comment by jtannas** [comment]
Thanks for the tip on the 'pass'.
The sphinx part is taking longer for me to figure out, but I've got it going in a test project.
Now to figure out how to document the modules and the application seperately :-S

**Comment by jtannas** [comment]
Progress update note to self:
- ReadTheDocs (http://noa.readthedocs.io/en/latest/index.html) is failing because the environment keys are not set
- Look into using http://www.sphinx-doc.org/en/stable/ext/napoleon.html for writing the docstrings
- General Notes: https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/

**Comment by jtannas** [comment]
Progress Notes:
- The Read the docs is now working correctly
- For readability, I will be using Google style docstrings and sphinx.ext.napoleon
- Starting to document python modules and cleaning up the accompanying .rst files

**Comment by jtannas** [comment]
@jsbath Is it sad it took me over a month and a course in python to figure out Sphinx?
